name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "We acknowledge the opening of your first issue with gratitude. You will hear from our team regarding this issue soon."
        pr-message: "We embrace your collaboration through this pull request and look forward to achieving great things."
